# Generated by Django 5.1.6 on 2025-02-13 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cart_added_at_cart_price_cart_product_cart_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
